### ISSUE TITLE
药品说明书页面，点进来的时候，上面的Banner错乱

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#16]
- [ ] 进来时错乱
- [ ] 图片尺寸没有按照设计图
- [ ] 轮播样式没有按照设计图

![image](https://user-images.githubusercontent.com/1689135/53147077-6af70c80-35e1-11e9-8395-cce795321a24.png)

**Comment by 110440** [comment]
OK
