### ISSUE TITLE
聊天界面顶部提示收费的价格和实际不一致

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#27]
![image](https://user-images.githubusercontent.com/1689135/53540116-2cb49c80-3b4f-11e9-853f-bbe0a3d3ec08.png)

![image](https://user-images.githubusercontent.com/1689135/53540124-39d18b80-3b4f-11e9-8e70-5d485562f7b2.png)

**Comment by 110440** [comment]
OK
