### ISSUE TITLE
个人中心-个人信息的状态判断不对

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#29]
如果半身白大褂、执业证、工牌三个证都通过审核了，则显示已认证状态。
![image](https://user-images.githubusercontent.com/1689135/53548616-e4a47280-3b6c-11e9-8b2a-0a9a0fde1b30.png)

![image](https://user-images.githubusercontent.com/1689135/53548496-8aa3ad00-3b6c-11e9-8d76-ca0c338fc61d.png)

**Comment by 110440** [comment]
OK
