### ISSUE TITLE
聊天界面样式错乱

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#31]
重现步骤：我的患者-点击任意患者-点击发消息，打开聊天界面，样式就这样了。
PS：从“我的服务”直接点开，样式正常

![image](https://user-images.githubusercontent.com/1689135/53721757-f785b280-3e9e-11e9-9da1-d527481a8570.png)

**Comment by 110440** [comment]
暂时没有重现

**Comment by ilaipi** [comment]
在xs max上是必现的
