### ISSUE TITLE
聊天界面实现按钮功能

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#32]
- [ ] 红色圈，点击效果和点击用户头像保持一致
- [ ] 蓝色圈，点击后打开单独改价页面（右上角的已经实现）
- [ ] 黄色圈，续方流程处理
- [ ] 绿色圈，结束会话（注意弹窗确认）接口

![image](https://user-images.githubusercontent.com/1689135/53778542-1421f900-3f38-11e9-817e-5de8d76a5d69.png)

**Comment by 110440** [comment]
OK
