### ISSUE TITLE
处方发送成功后，关闭处方页面，回到与患者聊天的对话框

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#37]
现在发送成功后仍然停留在处方页面，可以一直点发送

**Comment by 110440** [comment]
这个一直都是这样的，你是怎么点出来的

**Comment by ilaipi** [comment]
在处方页面，点击”添加药品“，然后点”购物车“按钮，这时候点发送，就不会回到聊天对话页面了

**Comment by 110440** [comment]
这个要考滤下这里再点 ”添加药品“ 后，，还要不要显示购物车，，不然可以一直循环点”购物车“—>”添加药品“   一直循环下去

**Comment by ilaipi** [comment]
循环下去有问题吗？这里理论上来讲是可以一直循环的。

发送之后跳回聊天页面，跟这里循环有关？能不能无视这里的循环，点发送就要跳回对话框。

**Comment by 110440** [comment]
OK, 我改下点  ”添加药品“  弹出方式
