### ISSUE TITLE
我的药房，处方笺，新建处方笺，药品列表判断是否已加入处方笺

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#51]
现在判断错了。应该是同一个药品在一个处方笺中只能出现一次，但是可以出现在多个处方笺中。

![image](https://user-images.githubusercontent.com/1689135/55457903-f4a4eb80-561d-11e9-8c36-4d4141712ca2.png)

**Comment by 110440** [comment]
怎么样出现的

**Comment by ilaipi** [comment]
我的药房-处方笺-新建常用处方-添加药品

选择第一个一级分类的第一个二级分类，出现的药品列表就是这样。

110440 <notifications@github.com> 于2019年4月4日周四 上午9:42写道：

**Comment by ilaipi** [comment]
已加入处方笺的，显示灰色的“移出处方笺”

未加入处方笺的，显示绿色的“加入处方笺”

**Comment by 110440** [comment]
OK
