### ISSUE TITLE
聊天界面咨询费显示有问题

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#55]
医生对秦思源5的设置显示的是免费：

![image](https://user-images.githubusercontent.com/1689135/56020114-fc107700-5d38-11e9-9b53-9603863cf071.png)

点立即设置，里面显示的是 0元/次

对刘东的设置显示的是0元/次：

![image](https://user-images.githubusercontent.com/1689135/56020175-206c5380-5d39-11e9-8179-875488a02973.png)

点立即设置，里面显示的是0.1元/次

**Comment by 110440** [comment]
OK
