### ISSUE TITLE
药瓶说明书界面，字段放错了

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#60]
第一个应该是取`name`，现在取的应该是`company`

第二个应该是取`common`，现在取的应该是`name`

健康指数的值，应该是取`remark`字段

![image](https://user-images.githubusercontent.com/1689135/56267932-c8f82a00-6122-11e9-80f5-8559b0ab91a2.png)

**Comment by ilaipi** [comment]
第一行的字段顺序：  
`name common specification`  
如果过长，可以换行显示。

**Comment by 110440** [comment]
OK
