### ISSUE TITLE
个人信息，工作证/工牌，通过审核的情况

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#78]
通过审核，点击，屏幕变暗了，本来这里是有个弹窗的，但是没弹出来。

**Comment by 110440** [comment]
什么系统的

**Comment by ilaipi** [comment]
xs max ios 12.2

110440 <notifications@github.com> 于2019年4月24日周三 上午11:24写道：

**Comment by 110440** [comment]
不关系统事，你是不是在这删除了个电话号码。。。。布局出错
