### ISSUE TITLE
患者详细资料页面

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#81]
显示患者的病种信息，在备注下面，不可编辑。

后端返回`[ '高血压', '糖尿病' ]`，前端显示`高血压，糖尿病`

**Comment by 110440** [comment]
没返回这个数据

**Comment by ilaipi** [comment]
@lhwu 会改文档的

110440 <notifications@github.com> 于2019年4月25日周四 上午10:16写道：

**Comment by lhwu** [comment]
医生端 11.3.1 添加 `diseases` 字段

**Comment by 110440** [comment]
OK
