### ISSUE TITLE
查看患者和医助的聊天记录页面优化

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#85]
- [ ] 顶部，下拉是刷新，和进来的时候请求一样。请求第一页的数据，并把响应替换当前数据
- [ ] 底部，上拉是翻页
- [ ] 渲染图片、语音消息
- [ ] 续方申请类的消息，显示预览即可

**Comment by lhwu** [comment]
图片：image,
语音：voice,
处方笺：rp,
续方：apply

**Comment by 110440** [comment]
ok
