### ISSUE TITLE
个人中心-我的账户-已入账积分统计，传参好像有问题

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#89]
`/sapi/hcp/bonus/record?end=1556347316.754584&start=1555828916.754584`

怎么会有小数？

**Comment by ilaipi** [comment]
传参规则

- start   当天-7 的0点0分0秒    
- end 次日的0点0分0秒

**Comment by 110440** [comment]
文档更新一下

**Comment by lhwu** [comment]
应该为毫秒的时间戳，13位整数

**Comment by 110440** [comment]
OK
